name: Check PR to develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular project
        run: npm run build


      - name: Start the Angular development server
        run: |
          npm install -g @angular/cli
          ng serve --host 0.0.0.0 --port 4200 &
        env:
          CI: true

      - name: Wait for the server to be ready
        run: |
          sleep 10
          curl --retry 10 --retry-connrefused --retry-delay 5 --max-time 120 -v http://localhost:4200
